# Generated by Django 3.0.7 on 2020-06-13 11:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_date', models.DateTimeField(auto_now_add=True)),
                ('u_date', models.DateTimeField(auto_now=True)),
                ('name', models.UUIDField(blank=True, default=uuid.UUID('b8e3bef3-7af2-4bb3-9985-730541dcf7f0'), unique=True)),
                ('api_key', models.CharField(max_length=25)),
                ('api_secret', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
