# Generated by Django 3.0.7 on 2020-06-13 22:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.UUIDField(blank=True, default=uuid.UUID('5a428e59-a8a7-455c-8b73-b3a0c7f4fe39'), unique=True),
        ),
    ]
