# Generated by Django 3.0.7 on 2020-06-13 23:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200613_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.UUIDField(blank=True, default=uuid.UUID('ca1294e5-46aa-43d5-9ca8-f8f5acc97bb5'), unique=True),
        ),
    ]
