# Generated by Django 3.0.7 on 2020-06-13 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_date', models.DateTimeField(auto_now_add=True)),
                ('u_date', models.DateTimeField(auto_now=True)),
                ('order_id', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('volume', models.IntegerField()),
                ('timestamp', models.CharField(blank=True, max_length=20)),
                ('side', models.CharField(max_length=10)),
                ('price', models.PositiveSmallIntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
