# Generated by Django 3.0.7 on 2020-06-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200613_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('canceled', 'Canceled'), ('failed', 'Failed')], default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='side',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=5),
        ),
    ]
